version: '2.0'

networks:
  app-tier:
    driver: bridge

services:
  myapp:
    image: 'chatapp'
    networks:
      - app-tier
    links:
      - mongodb
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo'
    networks:
      - app-tier
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 27018:27017
  