version: '3.9'

networks:
  app-tier:
    driver: bridge

services:

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
    container_name: db

  myapp:
    build: ./
    container_name: chatapp
    networks:
      - app-tier
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db